# Generated by Django 4.1.1 on 2022-10-07 22:23

import accounts.models
import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=accounts.models.profile_path, validators=[accounts.validators.validate_image]),
        ),
    ]
