# Generated by Django 4.1.1 on 2022-11-18 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userfriends_user_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='people',
        ),
    ]
