# Generated by Django 4.1.1 on 2022-11-18 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='people',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userfriends'),
        ),
    ]
