# Generated by Django 4.1.1 on 2022-10-07 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_creator_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='creator',
        ),
    ]
