# Generated by Django 4.1.1 on 2022-10-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_rename_user_comment_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='saved_by',
            new_name='saved',
        ),
    ]
