# Generated by Django 4.1.1 on 2022-10-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_rename_saved_by_post_saved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='saved',
            new_name='saves',
        ),
    ]
