# Generated by Django 4.1.1 on 2022-12-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_comment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isEdited',
            field=models.BooleanField(default=False),
        ),
    ]
